#pragma once

#define KERNBASE 0x80000000L

#define PAGE_SIZE 		  4096
#define MAX_VIRTUAL_ADDR ((1L << (38)))
#define TRAMPOLINE_COMMMON_REGION (MAX_VIRTUAL_ADDR - PAGE_SIZE)
#define KERNELEND 		  (BASEADDDRKERNEL + (128*1024*1024)) 
#define TRAPFRAME (TRAMPOLINE_COMMMON_REGION - PAGE_SIZE)
// void UART_SEND(const char *str);